# Generated by Django 4.0.6 on 2022-09-28 16:33

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('kingdom', models.CharField(max_length=50)),
                ('squad', models.CharField(max_length=100)),
                ('help', models.TextField()),
            ],
        ),
    ]
